export const movies = [
  {
    Title: 'Wonder Woman',
    Year: '2017',
    Genre: 'Action, Adventure, Fantasy',
    Plot: 'When a pilot crashes and tells of conflict in the outside world, Diana, an Amazonian warrior in training, leaves home to fight a war, discovering her full powers and true destiny.',
    PlotFull: `In 1984, after saving the world in Wonder Woman (2017), the immortal Amazon warrior, Princess Diana of Themyscira, finds herself trying to stay under the radar, working as an archaeologist at the Smithsonian Museum. With the memory of the brave U.S. pilot, Captain Steve Trevor, etched on her mind, Diana Prince becomes embroiled in a sinister conspiracy of global proportions when a transparent, golden-yellow citrine gemstone catches the eye of the power-hungry entrepreneur, Maxwell Lord. Now, as a dear old friend from the past miraculously enters the picture, and Barbara Minerva, Diana's insecure gemologist colleague gives in to desire, suddenly, deceit, greed, and false promises catapult Maxwell into the limelight. More and more, cataclysmic events push the world to the brink, and emotionally vulnerable Diana must address a cruel dilemma. Can mighty Wonder Woman save humankind once again?`,
    Poster: `https://m.media-amazon.com/images/M/MV5BMjEzYmZkNjktODBmYi00NzNkLWIzMjItMjhkMWZiZTZlN2MwXkEyXkFqcGc@._V1_SX300.jpg`,
    PosterHi: `https://m.media-amazon.com/images/M/MV5BMjEzYmZkNjktODBmYi00NzNkLWIzMjItMjhkMWZiZTZlN2MwXkEyXkFqcGc@._V1_SX1440.jpg`,
    imdbRating: '7.3',
    _id: 'tt8774790',
  },
  {
    Title: 'Below Zero',
    Year: '2021',
    Genre: 'Action, Drama, Thriller',
    Plot: 'On a lonely road, a prison transport is brutally assaulted. Martin, the policeman who was driving, survives and fortifies his position while the con men search for a way to finish him.',
    Poster: `https://m.media-amazon.com/images/M/MV5BNDc5ZTc0OGYtNGRjMC00MDI0LWI3ZDQtZmU4ODc4NDRjZWQwXkEyXkFqcGc@._V1_SX300.jpg`,
    PosterHi: `https://m.media-amazon.com/images/M/MV5BNDc5ZTc0OGYtNGRjMC00MDI0LWI3ZDQtZmU4ODc4NDRjZWQwXkEyXkFqcGc@._V1_SX1440.jpg`,
    imdbRating: '6.2',
    _id: 'tt8774791',
  },
  {
    Title: 'The Little Things',
    Year: '2021',
    Genre: 'Crime, Drama, Mystery',
    Plot: 'Kern County Deputy Sheriff Joe Deacon is sent to Los Angeles for what should have been a quick evidence-gathering assignment. Instead, he becomes embroiled in the search for a serial killer who is terrorizing the city.',
    PlotFull: `Deke (Denzel Washington), a burnt-out Kern County, CA deputy sheriff teams up with Baxter (Rami Malek), a crack LASD detective, to nab a serial killer. Deke's nose for the \"little things\" proves eerily accurate, but his willingness to circumvent the rules embroils Baxter in a soul-shattering dilemma. Meanwhile, Deke must wrestle with a dark secret from his past.`,
    Poster: `https://m.media-amazon.com/images/M/MV5BZmRjYmQ5Y2YtYTUyMy00OTg0LWE1YmEtZTI2NDYxYTBhYTYxXkEyXkFqcGc@._V1_SX300.jpg`,
    PosterHi: `https://m.media-amazon.com/images/M/MV5BZmRjYmQ5Y2YtYTUyMy00OTg0LWE1YmEtZTI2NDYxYTBhYTYxXkEyXkFqcGc@._V1_SX1440.jpg`,
    imdbRating: '6.3',
    _id: 'tt8774792',
  },
  {
    Title: 'Outside the Wire',
    Year: '2021',
    Genre: 'Crime, Drama, Mystery',
    Plot: 'In the near future, a drone pilot sent into a war zone finds himself paired with a top-secret android officer on a mission to stop a nuclear attack.',
    PlotFull: `When disgraced drone pilot, Lt. Harp (Damson Idris) is sent into a deadly militarized zone after disobeying orders, he finds himself working for Capt. Leo (Anthony Mackie), an android officer tasked with locating a doomsday device before insurgents do.`,
    Poster: `https://m.media-amazon.com/images/M/MV5BZTM2ZTFjMTctNmJjNS00OTkwLWIxOWEtY2NjMDI3NTJmNmMxXkEyXkFqcGc@._V1_SX300.jpg`,
    PosterHi: `https://m.media-amazon.com/images/M/MV5BZTM2ZTFjMTctNmJjNS00OTkwLWIxOWEtY2NjMDI3NTJmNmMxXkEyXkFqcGc@._V1_SX1440.jpg`,
    imdbRating: '5.4',
    _id: 'tt8774793',
  },
  {
    Title: 'Black Water: Abyss',
    Year: '2020',
    Genre: 'Adventure, Horror, Thriller',
    Plot: 'Five friends exploring a remote cave system in Northern Australia find themselves threatened by a hungry crocodile.',
    Poster: `https://m.media-amazon.com/images/M/MV5BNTE3YWQzZDMtN2E1Yi00M2VlLWI3MjUtZDEyYzgzOWFlYWU0XkEyXkFqcGc@._V1_SX300.jpg`,
    PosterHi: `https://m.media-amazon.com/images/M/MV5BNTE3YWQzZDMtN2E1Yi00M2VlLWI3MjUtZDEyYzgzOWFlYWU0XkEyXkFqcGc@._V1_SX1440.jpg`,
    imdbRating: '4.6',
    _id: 'tt8774794',
  },
  {
    Title: 'Breach',
    Year: '2020',
    Genre: 'Action, Horror, Sci-Fi',
    Plot: 'On the cusp of fatherhood, a junior mechanic aboard an interstellar ark to New Earth must outwit a malevolent cosmic terror intent on using the spaceship as a weapon.',
    Poster: `https://m.media-amazon.com/images/M/MV5BMjdlMmFlZWEtZjFhZC00NmRiLTkzYzYtMmYzYzQzMjRmZWE4XkEyXkFqcGc@._V1_SX300.jpg`,
    PosterHi: `https://m.media-amazon.com/images/M/MV5BMjdlMmFlZWEtZjFhZC00NmRiLTkzYzYtMmYzYzQzMjRmZWE4XkEyXkFqcGc@._V1_SX1440.jpg`,
    imdbRating: '2.9',
    _id: 'tt8774795',
  },
  {
    Title: 'Soul',
    Year: '2020',
    Genre: 'Animation, Adventure, Comedy',
    Plot: `Joe is a middle-school band teacher whose life hasn't quite gone the way he expected. His true passion is jazz. But when he travels to another realm to help someone find their passion, he soon discovers what it means to have soul.`,
    Poster: `https://m.media-amazon.com/images/M/MV5BZTZkYjA5MDEtMjY1ZC00ODk5LThjOTUtZDYxODEzYWNjMTU2XkEyXkFqcGc@._V1_SX300.jpg`,
    PosterHi: `https://m.media-amazon.com/images/M/MV5BZTZkYjA5MDEtMjY1ZC00ODk5LThjOTUtZDYxODEzYWNjMTU2XkEyXkFqcGc@._V1_SX1440.jpg`,
    imdbRating: '8.0',
    _id: 'tt8774796',
  },
  {
    Title: 'Fast & Furious Presents: Hobbs & Shaw',
    Year: '2019',
    Genre: 'Action, Adventure, Thriller',
    Plot: `Lawman Luke Hobbs and outcast Deckard Shaw form an unlikely alliance when a cyber-genetically enhanced villain threatens the future of humanity.`,
    Poster: `https://m.media-amazon.com/images/M/MV5BNmU4OTA5NGYtMTFjMS00MzgxLWFjNTMtYjdlMThlYzc4M2M4XkEyXkFqcGc@._V1_SX300.jpg`,
    PosterHi: `https://m.media-amazon.com/images/M/MV5BNmU4OTA5NGYtMTFjMS00MzgxLWFjNTMtYjdlMThlYzc4M2M4XkEyXkFqcGc@._V1_SX1440.jpg`,
    imdbRating: '6.5',
    _id: 'tt8774797',
  },
  {
    Title: 'The Croods: A New Age',
    Year: '2020',
    Genre: 'Animation, Adventure, Comedy',
    Plot: `The prehistoric family the Croods are challenged by a rival family the Bettermans, who claim to be better and more evolved.`,
    Poster: `https://m.media-amazon.com/images/M/MV5BZTI1OTFhYmQtMzM4NS00Y2NkLTlkMmEtNTJhMWU1YWI0ZGQ2XkEyXkFqcGc@._V1_SX300.jpg`,
    PosterHi: `https://m.media-amazon.com/images/M/MV5BZTI1OTFhYmQtMzM4NS00Y2NkLTlkMmEtNTJhMWU1YWI0ZGQ2XkEyXkFqcGc@._V1_SX1440.jpg`,
    imdbRating: '6.9',
    _id: 'tt8774798',
  },
  {
    Title: 'Vanguard',
    Year: '2020',
    Genre: 'Action, Adventure, Comedy',
    Plot: `Covert security company Vanguard is the last hope of survival for an accountant after he is targeted by the world's deadliest mercenary organization.`,
    Poster: `https://m.media-amazon.com/images/M/MV5BOTk5ZjQwZmMtZmFhZi00MDY4LThmYzctODc0MGQ2ODhkY2U3XkEyXkFqcGc@._V1_SX300.jpg`,
    PosterHi: `https://m.media-amazon.com/images/M/MV5BOTk5ZjQwZmMtZmFhZi00MDY4LThmYzctODc0MGQ2ODhkY2U3XkEyXkFqcGc@._V1_SX1440.jpg`,
    imdbRating: '4.7',
    _id: 'tt8774799',
  },
  {
    Title: 'Tenet',
    Year: '2020',
    Genre: 'Action, Sci-Fi, Thriller',
    Plot: `Armed with only the word \"Tenet,\" and fighting for the survival of the entire world, CIA operative, The Protagonist, journeys through a twilight world of international espionage on a global mission that unfolds beyond real time.`,
    Poster: `https://m.media-amazon.com/images/M/MV5BMTU0ZjZlYTUtYzIwMC00ZmQzLWEwZTAtZWFhMWIwYjMxY2I3XkEyXkFqcGc@._V1_SX300.jpg`,
    PosterHi: `https://m.media-amazon.com/images/M/MV5BMTU0ZjZlYTUtYzIwMC00ZmQzLWEwZTAtZWFhMWIwYjMxY2I3XkEyXkFqcGc@._V1_SX1440.jpg`,
    imdbRating: '7.3',
    _id: 'tt8774800',
  },
  {
    Title: '100% Wolf',
    Year: '2020',
    Genre: 'Animation, Adventure, Comedy',
    Plot: `100% Wolf centers on Freddy Lupin, heir to a proud family line of werewolves. Positive he'll become the most fearsome werewolf ever, Freddy is in for a shock when his first \"warfing\" goes awry, turning him into a ferocious - poodle.`,
    Poster: `https://m.media-amazon.com/images/M/MV5BMTZkODJhNzAtNTYxMS00ZTNlLThhNWQtY2U5NTlkZDc4NzE5XkEyXkFqcGc@._V1_SX300.jpg`,
    PosterHi: `https://m.media-amazon.com/images/M/MV5BMTZkODJhNzAtNTYxMS00ZTNlLThhNWQtY2U5NTlkZDc4NzE5XkEyXkFqcGc@._V1_SX1440.jpg`,
    imdbRating: '5.6',
    _id: 'tt8774801',
  },
  {
    Title: 'The Old Guard',
    Year: '2020',
    Genre: 'Action, Thriller',
    Plot: `A covert group of tight-knit mercenaries with an inability to die have fought to protect the world for centuries. But when their abilities are suddenly exposed, they need to eliminate the threat of those who seek to replicate.`,
    Poster: `https://m.media-amazon.com/images/M/MV5BYzMwNjVjNTEtZDVhOC00NzQzLTg0MGYtMGI1Yzc0Nzg2MjNmXkEyXkFqcGc@._V1_SX300.jpg`,
    PosterHi: `https://m.media-amazon.com/images/M/MV5BYzMwNjVjNTEtZDVhOC00NzQzLTg0MGYtMGI1Yzc0Nzg2MjNmXkEyXkFqcGc@._V1_SX1440.jpg`,
    imdbRating: '6.7',
    _id: 'tt8774802',
  },
  {
    Title: 'Poject Power',
    Year: '2020',
    Genre: 'Action, Crime, Sci-Fi',
    Plot: `When a pill that gives its users unpredictable superpowers for five minutes hits the streets of New Orleans, a teenage dealer and a local cop must team with an ex-soldier to take down the group responsible for its creation.`,
    PlotFull: `On the streets of New Orleans, word begins to spread about a mysterious new pill that unlocks superpowers unique to each user. The catch: You don't know what will happen until you take it. While some develop bulletproof skin, invisibility, and super strength, others exhibit a deadlier reaction. But when the pill escalates crime within the city to dangerous levels, a local cop (Joseph Gordon-Levitt) teams with a teenage dealer (Dominique Fishback) and a former soldier fueled by a secret vendetta (Jamie Foxx) to fight power with power and risk taking the pill in order to track down and stop the group responsible for creating it.`,
    Poster: `https://m.media-amazon.com/images/M/MV5BM2QxNjM4YTAtMjY1Yi00YjMwLTlkOWUtZmIzYmZmNzUwNDU1XkEyXkFqcGc@._V1_SX300.jpg`,
    PosterHi: `https://m.media-amazon.com/images/M/MV5BM2QxNjM4YTAtMjY1Yi00YjMwLTlkOWUtZmIzYmZmNzUwNDU1XkEyXkFqcGc@._V1_SX1440.jpg`,
    imdbRating: '6.0',
    _id: 'tt7550000',
  },
];